import "~/styles/globals.css";

import { Kulim_Park } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import NavBar from "./_components/NavBar";

const inter = Kulim_Park({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: "200",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="lofi">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <NavBar />
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
